parameters:
    krtv.csrf_validator.subscriber.class: Krtv\Bundle\CsrfValidatorBundle\EventListener\AnnotationSubscriber
    krtv.csrf_validator.reader_manager.class: Krtv\Bundle\CsrfValidatorBundle\ReaderManager\AnnotationReaderManager

services:
    krtv.csrf_validator.reader_manager:
        class: %krtv.csrf_validator.reader_manager.class%
        arguments: [@annotation_reader, @form.csrf_provider, @service_container]
        scope: request

    krtv.csrf_validator.subscriber:
        class: %krtv.csrf_validator.subscriber.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }